gui:
  # nu_disco
  theme:
    lightTheme: false
    activeBorderColor:
      - "#52E7E1"
      - bold
    inactiveBorderColor:
      - "#BDB7BD" # Text
    optionsTextColor:
      - "#6BB5FF" # Blue
    selectedLineBgColor:
      - "#313244" # Surface0
    selectedRangeBgColor:
      - "#313244" # Surface0
    cherryPickedCommitBgColor:
      - "#52E7E1" # Teal
    cherryPickedCommitFgColor:
      - "#6BB5FF" # Blue
    unstagedChangesColor:
      - "#FF7878" # Red
  authorColors:
    "Károly Török": "#52E7E1" # Pink dark

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --pretty='%C(red)%h%Creset%C(yellow)%d%Creset %s %C(cyan)(%ar)%Creset' {{branchName}} --"
